CREATE TABLE IF NOT EXISTS film
(
      id integer GENERATED ALWAYS AS IDENTITY,
      name VARCHAR(100) NOT NULL,
      description VARCHAR(200) NOT NULL,
      mpa_id INTEGER NOT NULL,
      release_date DATE NOT NULL,
      duration INTEGER NOT NULL,
      likes_amount INTEGER,
      CONSTRAINT film_pk PRIMARY KEY (id),
      CONSTRAINT films_fk FOREIGN KEY (mpa_id) REFERENCES mpa
);


CREATE TABLE IF NOT EXISTS mpa
(
      mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
      mpa_name VARCHAR(20) NOT NULL,
      CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id integer GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(50) NOT  NULL,
    name VARCHAR(50),
    login VARCHAR(50) NOT NULL,
    birthdate DATE,
    CONSTRAINT user_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id integer GENERATED ALWAYS AS IDENTITY,
    genre_name VARCHAR(50),
    CONSTRAINT genre_pk PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT film_fk FOREIGN KEY (film_id) REFERENCES film,
    CONSTRAINT genre_fk FOREIGN KEY (genre_id) REFERENCES genre
);

CREATE TABLE IF NOT EXISTS friends
(
    first_user_id INTEGER NOT NULL,
    second_user_id INTEGER NOT NULL,
    CONSTRAINT first_user_fk FOREIGN KEY (first_user_id) REFERENCES users(id),
    CONSTRAINT second_user_fk FOREIGN KEY (second_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT user_like_fk FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT film_like_fk FOREIGN KEY(film_id) REFERENCES film(id)
);

